# Generated by Django 3.0.1 on 2020-05-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations_api', '0002_mynotebook_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynotebook',
            name='year_in_school',
        ),
    ]
